server:
  port: 9194

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qwe123qwe
      
  jpa:
    hibernate:
      ddl-auto: update
      
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration:5

      
